优化

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -49,3 +49,16 @@ scandir() {
     fi
   done
 }
+
+# 检查命令是否存在
+program_exists() {
+    local ret='0'
+    command -v $1 >/dev/null 2>&1 || { local ret='1'; }
+
+    # fail on non-zero return value
+    if [ "$ret" -ne 0 ]; then
+        return 1
+    fi
+
+    return 0
+}
