优化

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -52,13 +52,58 @@ scandir() {
 
 # 检查命令是否存在
 program_exists() {
-    local ret='0'
-    command -v $1 >/dev/null 2>&1 || { local ret='1'; }
+  local ret='0'
+  command -v $1 >/dev/null 2>&1 || { local ret='1'; }
 
-    # fail on non-zero return value
-    if [ "$ret" -ne 0 ]; then
-        return 1
-    fi
+  # fail on non-zero return value
+  if [ "$ret" -ne 0 ]; then
+    return 1
+  fi
 
-    return 0
+  return 0
+}
+
+# 获取不同格式的当前日期时间
+get_datetime() {
+  case $1 in
+  'n')
+    echo $(date '+%Y%m%d%H%M%S')
+    ;;
+  '-')
+    echo $(date '+%Y-%m-%d-%H-%M-%S')
+    ;;
+  '/')
+    echo $(date '+%Y/%m/%d %H:%M:%S')
+    ;;
+  '_')
+    echo $(date '+%Y_%m_%d_%H_%M_%S')
+    ;;
+  'd')
+    echo $(date '+%Y%m%d')
+    ;;
+  '-d')
+    echo $(date '+%Y-%m-%d')
+    ;;
+  '/d')
+    echo $(date '+%Y/%m/%d')
+    ;;
+  '_d')
+    echo $(date '+%Y_%m_%d')
+    ;;
+  't')
+    echo $(date '+%H%M%S')
+    ;;
+  '-t')
+    echo $(date '+%H-%M-%S')
+    ;;
+  ':t')
+    echo $(date '+%H:%M:%S')
+    ;;
+  '_t')
+    echo $(date '+%H_%M_%S')
+    ;;
+  *)
+    echo $(date '+%Y-%m-%d %H:%M:%S')
+    ;;
+  esac
 }
